name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file unRAID/Dockerfile --tag eddcase/windward-horizon-server:unraid
    - name: Dockerhub Login
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
    - name: Push the Docker image
      run: docker push eddcase/windward-horizon-server:unraid
